#ifndef WIDGETS_H
#define WIDGETS_H

#include "label.h"
#include "button.h"
#include "checkbox.h"
#include "radio.h"
#include "textbox.h"
#include "dropdown.h"
#include "slider.h"
#include "progress.h"
#include "groupbox.h"
#include "tab.h"
#include "tree.h"
#include "table.h"
#include "field_border.h"
#include "status_field.h"
#include "sunken_panel.h"
#include "vbox.h"
#include "hbox.h"
#include "separator.h"
#include "spinbox.h"
#include "combobox.h"
#include "textedit.h"
#include "listbox.h"
#include "menubar.h"
#include "toolbar.h"
#include "image.h"
#include "scroll_area.h"
#include "stacked.h"
#include "tab_widget.h"
#include "accordion.h"
#include "tooltip.h"
#include "dialog.h"

#endif /* WIDGETS_H */
